
SET NAMES utf8mb4;
SET FOREIGN_KEY_CHECKS = 0;
TRUNCATE TABLE audit_logs;
TRUNCATE TABLE graduation;
TRUNCATE TABLE rewards;
TRUNCATE TABLE scores;
TRUNCATE TABLE changes;
TRUNCATE TABLE students;
TRUNCATE TABLE users;
SET FOREIGN_KEY_CHECKS = 1;
